import uuid
from datetime import date, datetime, timedelta
from zoneinfo import ZoneInfo

import pytest
from httpx import AsyncClient
from sqlalchemy import insert, update

from app.db.session import async_session_factory
from app.models.habit import Habit
from app.models.occurrence import Occurrence, OccurrenceStatus

pytestmark = pytest.mark.asyncio

def auth_headers(token: str) -> dict:
    return {"Authorization": f"Bearer {token}"}

async def create_user_and_token(client: AsyncClient, tz: str = "UTC") -> tuple[str, str]:
    email = f"user_{uuid.uuid4()}@example.com"
    res = await client.post(
        "/api/v1/auth/register",
        json={"email": email, "password": "strongpassword123", "display_name": "Test User", "timezone": tz},
    )
    assert res.status_code == 201
    return res.json()["tokens"]["access_token"], res.json()["user"]["id"]

async def test_streak_d10_d11_longest_total(client: AsyncClient):
    token, user_id = await create_user_and_token(client, "UTC")
    today = datetime.now(ZoneInfo("UTC")).date()
    start_date = today - timedelta(days=10)

    # Create habit (custom schedule, every day)
    res = await client.post(
        "/api/v1/habits",
        headers=auth_headers(token),
        json={
            "name": "Streak Habit",
            "frequency": "daily",
            "days_of_week": [0, 1, 2, 3, 4, 5, 6],
            "start_date": today.isoformat(),
        },
    )
    assert res.status_code == 201
    habit_id = res.json()["id"]
    
    async with async_session_factory() as db:
        stmt = update(Habit).where(Habit.id == habit_id).values(start_date=start_date)
        await db.execute(stmt)
        from app.models.schedule import Schedule
        stmt2 = update(Schedule).where(Schedule.habit_id == habit_id).values(effective_from=start_date)
        await db.execute(stmt2)
        await db.commit()
    
    # We will seed the db with 5 past occurrences
    # T-5: completed
    # T-4: completed
    # T-3: skipped (breaks streak)
    # T-2: completed
    # T-1: completed
    # T-0: pending (today, already generated by Phase 4 logic)
    
    past_dates = [
        (today - timedelta(days=5), OccurrenceStatus.completed),
        (today - timedelta(days=4), OccurrenceStatus.completed),
        (today - timedelta(days=3), OccurrenceStatus.skipped),
        (today - timedelta(days=2), OccurrenceStatus.completed),
        (today - timedelta(days=1), OccurrenceStatus.completed),
    ]
    
    async with async_session_factory() as db:
        for d, status in past_dates:
            stmt3 = insert(Occurrence).values(
                habit_id=habit_id,
                occurrence_date=d,
                status=status
            )
            await db.execute(stmt3)
        await db.commit()
        
    # Get today's occurrence id
    res = await client.get("/api/v1/today", headers=auth_headers(token))
    data = res.json()
    today_occ_id = data["occurrences"][0]["id"]
    
    # Trigger a status mutation to force recalculation
    headers = auth_headers(token)
    headers["Idempotency-Key"] = str(uuid.uuid4())
    res = await client.put(
        f"/api/v1/occurrences/{today_occ_id}",
        headers=headers,
        json={"status": "completed"}
    )
    assert res.status_code == 200
    
    # Now check stats
    res = await client.get(f"/api/v1/habits/{habit_id}/stats", headers=auth_headers(token))
    assert res.status_code == 200
    stats = res.json()
    
    # Streak should be: T-2, T-1, T-0 all completed -> 3
    assert stats["current_streak"] == 3
    # Longest streak: run from T-5 to T-4 was 2, run from T-2 to T-0 is 3 -> 3
    assert stats["longest_streak"] == 3
    # Total completions: 5
    assert stats["total_completions"] == 5
    
    # Test undo (completed -> pending for today)
    headers_undo = auth_headers(token)
    headers_undo["Idempotency-Key"] = str(uuid.uuid4())
    res = await client.put(
        f"/api/v1/occurrences/{today_occ_id}",
        headers=headers_undo,
        json={"status": "pending"},
    )
    assert res.status_code == 200
    
    # Check stats after undo
    res = await client.get(f"/api/v1/habits/{habit_id}/stats", headers=auth_headers(token))
    stats = res.json()
    
    # Streak should be: T-2, T-1 are completed, today is pending -> 2
    assert stats["current_streak"] == 2
    # Longest streak: still 2 from earlier run? No, wait. 
    # Longest streak recalculation scans history. 
    # Current run T-2 to T-1 is 2. Past run T-5 to T-4 is 2. Max is 2!
    assert stats["longest_streak"] == 2
    assert stats["total_completions"] == 4
    
    # Test MISSED breaks streak
    async with async_session_factory() as db:
        # Change T-1 to missed
        stmt = update(Occurrence).where(
            Occurrence.habit_id == habit_id, 
            Occurrence.occurrence_date == today - timedelta(days=1)
        ).values(status=OccurrenceStatus.missed)
        await db.execute(stmt)
        await db.commit()
        
    # Trigger recalculation by completing today again
    headers2 = auth_headers(token)
    headers2["Idempotency-Key"] = str(uuid.uuid4())
    res = await client.put(
        f"/api/v1/occurrences/{today_occ_id}",
        headers=headers2,
        json={"status": "completed"}
    )
    assert res.status_code == 200
    
    res = await client.get(f"/api/v1/habits/{habit_id}/stats", headers=auth_headers(token))
    stats = res.json()
    # T-1 is missed. So T-0 is the only current streak -> 1
    assert stats["current_streak"] == 1
    # Longest streak is 2 (from T-5 to T-4)
    assert stats["longest_streak"] == 2


async def test_calendar_and_account_stats(client: AsyncClient):
    token, user_id = await create_user_and_token(client, "UTC")
    today = datetime.now(ZoneInfo("UTC")).date()
    start_date = today - timedelta(days=10)

    # Create habit
    res = await client.post(
        "/api/v1/habits",
        headers=auth_headers(token),
        json={
            "name": "Calendar Habit",
            "frequency": "daily",
            "days_of_week": [0, 1, 2, 3, 4, 5, 6],
            "start_date": today.isoformat(),
        },
    )
    assert res.status_code == 201
    habit_id = res.json()["id"]
    
    async with async_session_factory() as db:
        stmt = update(Habit).where(Habit.id == habit_id).values(start_date=start_date)
        await db.execute(stmt)
        from app.models.schedule import Schedule
        stmt2 = update(Schedule).where(Schedule.habit_id == habit_id).values(effective_from=start_date)
        await db.execute(stmt2)
        await db.commit()
    
    # Complete today
    res = await client.get("/api/v1/today", headers=auth_headers(token))
    data = res.json()
    today_occ_id = data["occurrences"][0]["id"]
    
    headers_cal = auth_headers(token)
    headers_cal["Idempotency-Key"] = str(uuid.uuid4())
    res = await client.put(
        f"/api/v1/occurrences/{today_occ_id}",
        headers=headers_cal,
        json={"status": "completed"}
    )
    
    # Check calendar
    res = await client.get(f"/api/v1/calendar/summary?year={today.year}&month={today.month}", headers=auth_headers(token))
    assert res.status_code == 200
    cal_data = res.json()
    
    # Ensure every day of month is present
    days_in_month = (date(today.year, today.month + 1, 1) - timedelta(days=1)).day if today.month < 12 else 31
    assert len(cal_data["days"]) == days_in_month
    
    # Today should be scheduled=1, completed=1, percent=100
    today_data = next(d for d in cal_data["days"] if d["date"] == today.isoformat())
    assert today_data["scheduled"] == 1
    assert today_data["completed"] == 1
    assert today_data["percent"] == 100
    
    # Check account stats
    res = await client.get("/api/v1/stats/overview", headers=auth_headers(token))
    assert res.status_code == 200
    acct_data = res.json()
    
    assert acct_data["total_active_habits"] == 1
    assert acct_data["best_current_streak"] == 1
    assert acct_data["total_lifetime_completions"] == 1
