"""occurrences

Revision ID: 523ab14c2ddb
Revises: 0001
Create Date: 2026-09-25 16:49:52.362569
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '523ab14c2ddb'
down_revision: str | None = '0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('occurrences',
    sa.Column('habit_id', sa.UUID(), nullable=False),
    sa.Column('occurrence_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'completed', 'skipped', 'missed', name='occurrence_status', create_constraint=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('synced_from_offline', sa.Boolean(), nullable=False),
    sa.Column('idempotency_key', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['habit_id'], ['habits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('habit_id', 'occurrence_date', name='uq_occurrences_habit_date')
    )
    op.create_index('ix_occurrences_habit_date', 'occurrences', ['habit_id', 'occurrence_date'], unique=False)
    op.create_index('ix_occurrences_idempotency', 'occurrences', ['habit_id', 'idempotency_key'], unique=True, postgresql_where='idempotency_key IS NOT NULL')
    op.create_index('ix_occurrences_pending_date', 'occurrences', ['occurrence_date', 'status'], unique=False, postgresql_where="status = 'pending'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_occurrences_pending_date', table_name='occurrences', postgresql_where="status = 'pending'")
    op.drop_index('ix_occurrences_idempotency', table_name='occurrences', postgresql_where='idempotency_key IS NOT NULL')
    op.drop_index('ix_occurrences_habit_date', table_name='occurrences')
    op.drop_table('occurrences')
    # ### end Alembic commands ###
