"""streaks_and_stats

Revision ID: bd8da8c4ac34
Revises: 523ab14c2ddb
Create Date: 2026-09-26 23:01:59.683700
"""
from __future__ import annotations

from collections.abc import Sequence
from datetime import date, timedelta

import sqlalchemy as sa
from sqlalchemy.orm import Session

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'bd8da8c4ac34'
down_revision: str | None = '523ab14c2ddb'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('habits', sa.Column('current_streak', sa.Integer(), server_default='0', nullable=False))
    op.add_column('habits', sa.Column('longest_streak', sa.Integer(), server_default='0', nullable=False))
    op.add_column('habits', sa.Column('total_completions', sa.Integer(), server_default='0', nullable=False))
    
    # Backfill
    bind = op.get_bind()
    session = Session(bind=bind)
    
    # Simple backfill for total_completions
    session.execute(sa.text("""
        UPDATE habits h
        SET total_completions = (
            SELECT count(id) FROM occurrences o
            WHERE o.habit_id = h.id AND o.status = 'completed'
        )
    """))
    
    # For streaks, we iterate over all habits
    habits = session.execute(sa.text("SELECT id, start_date, user_id FROM habits")).mappings().fetchall()
    
    for h in habits:
        user_tz = session.execute(
            sa.text("SELECT timezone FROM users WHERE id = :uid"), 
            {"uid": h["user_id"]}
        ).scalar() or "UTC"
        
        # We need local today for user
        from datetime import datetime
        from zoneinfo import ZoneInfo
        local_today = datetime.now(ZoneInfo(user_tz)).date()
        
        # Get schedules
        schedules = session.execute(
            sa.text("SELECT effective_from, days_of_week FROM schedules WHERE habit_id = :hid ORDER BY effective_from DESC"),
            {"hid": h["id"]}
        ).mappings().fetchall()
        
        if not schedules:
            continue
            
        def get_applicable_sched(d: date, schedules=schedules):
            for s in schedules:
                if s["effective_from"] <= d:
                    return s
            return None
            
        scheduled_dates = []
        curr = local_today
        while curr >= h["start_date"]:
            sched = get_applicable_sched(curr)
            if sched and curr.weekday() in sched["days_of_week"]:
                scheduled_dates.append(curr)
            curr -= timedelta(days=1)
            
        # Get occurrences
        occs = session.execute(
            sa.text("SELECT occurrence_date, status FROM occurrences WHERE habit_id = :hid"),
            {"hid": h["id"]}
        ).mappings().fetchall()
        
        occ_map = {o["occurrence_date"]: o["status"] for o in occs}
        
        current_streak = 0
        longest_streak = 0
        current_broken = False
        current_run = 0
        
        for d in scheduled_dates:
            status = occ_map.get(d)
            if status == "completed":
                if not current_broken:
                    current_streak += 1
                current_run += 1
                if current_run > longest_streak:
                    longest_streak = current_run
            elif status == "pending" and d == local_today:
                continue
            else:
                current_broken = True
                current_run = 0
                
        session.execute(
            sa.text("UPDATE habits SET current_streak = :cs, longest_streak = :ls WHERE id = :hid"),
            {"cs": current_streak, "ls": longest_streak, "hid": h["id"]}
        )
        
    session.commit()
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('habits', 'total_completions')
    op.drop_column('habits', 'longest_streak')
    op.drop_column('habits', 'current_streak')
    # ### end Alembic commands ###
